---

# note that 'host = localhost' as we are using aws api for brand new instances
# Uses ec2 module to create a new host and add it to special 'ec2hosts' inventory group

- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    keypair: "id_rsa_macbook"
    instance_type: "t2.micro"
    image: "ami-33db9803"
    group: "aidan_custom_ips"
    wait: "true"
    region: "us-west-2"
  tasks:
    - name: make one instance
      ec2: image={{ image }}
            instance_type={{ instance_type }}
            keypair={{ keypair }}
            instance_tags='{"Name":"from_ansible"}'
            region={{ region }}
            group={{ group }}
            wait={{ wait }}
      register: ec2_info

    - debug: var=ec2_info
    - debug: var=item
      with_items: ec2_info.instance_ids

    - add_host: hostname={{ item.public_ip }} groupname=ec2hosts
      with_items: ec2_info.instances

    - name: 'wait for instances to listen on port: 22'
      wait_for:
        state=started
        host={{ item.public_dns_name }}
        port=22
      with_items: ec2_info.instances

