---

- name: Provision a set of instances
  ec2: >
      group={{security_group}}
      instance_type={{instance_type}}
      image={{image}}
      wait=true
      count={{number}}
    register: ec2

- name: Add all instances public IPs to host group
  add_host: hostname={{ item.public_ip }} groupname=ec2hosts
  with_items: ec2.instances


